const quizData = [
    {
        question: 'Что выведет в консоль?',
        a: '"false"',
        b: '1',
        c: 'true',
        d: '0',
        correct: 'a',
        id: '1',
    },
    {
        question: 'Какое значение будет в result?',
        a: 'null',
        b: '2',
        c: '3',
        d: 'undefined',
        correct: 'd',
        id: '2',
    },
    {
        question: 'Какое значение будет в result?',
        a: 'boolean',
        b: 'null',
        c: 'undefined',
        d: '0',
        correct: 'a',
        id: '3',
    },
    {
        question: 'Что выведет в консоль?',
        a: 'false',
        b: '"Аниме"',
        c: '0',
        d: '1',
        correct: 'b',
        id: '4',
    },
    {
        question: 'Какое значение будет в result?',
        a: 'null',
        b: '1',
        c: '2',
        d: 'throw a SyntaxError',
        correct: 'c',
        id: '5',
    },
    {
        question: 'Чему будет равно n?',
        a: '8',
        b: '6',
        c: '7',
        d: '9',
        correct: 'a',
        id: '6',
    },
    {
        question: 'Что выведет в консоль?',
        a: '2',
        b: 'undefined',
        c: '1',
        d: '"2"',
        correct: 'c',
        id: '7',
    },

    {
        question: 'Что выведет в консоль?',
        a: '10',
        b: 'throw a SyntaxError',
        c: 'undefined',
        d: '25',
        correct: 'a',
        id: '8',
    },
    {
        question: 'Что выведет в консоль?',
        a: '5',
        b: 'undefined',
        c: 'null',
        d: 'ReferenceError',
        correct: 'd',
        id: '9',
    },

    {
        question: 'Чему будет равно n?',
        a: '8',
        b: '7',
        c: '1',
        d: '4',
        correct: 'b',
        id: '10',
    },

    {
        question: 'Что выведет в консоль?',
        a: 'number',
        b: 'boolean',
        c: 'string',
        d: '5',
        correct: 'c',
        id: '11',
    },
    {
        question: 'Что выведет в консоль?',
        a: 'false',
        b: 'boolean',
        c: 'true',
        d: '"10"',
        correct: 'a',
        id: '12',
    },
    {
        question: 'Что выведет в консоль?',
        a: '12',
        b: '10',
        c: '9',
        d: '11',
        correct: 'd',
        id: '13',
    },
];

export default quizData;


